# -*- python -*-
from lsst.sconsUtils import scripts
scripts.BasicSConstruct("{{cookiecutter.repo_name|lower}}",
                        versionModuleName='python/desc/{{cookiecutter.repo_name|lower}}/version.py')
